config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.cern.ch/batistal/eosc-data-transfer-client:
      branch: main
      repo: https://gitlab.cern.ch/batistal/eosc-data-transfer-client
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client git:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_gentle_goat.sh
        container: qc.acc_strawberry_confident_wolf
  QC.Doc:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.marigold_diligent_leopard.sh
        container: qc.doc_cayenne_careful_turkey
      gitlab.cern.ch/batistal/eosc-data-transfer-client git:
        commands:
        - /usr/bin/env sh .sqa/script.onyx_reserved_albatross.sh
        container: qc.doc_rust_sincere_porpoise
      gitlab.cern.ch/batistal/eosc-data-transfer-client markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.iris_reserved_meerkat.sh
        container: qc.doc_gold_unique_warthog
  QC.Lic:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client licensee:
        commands:
        - /usr/bin/env sh .sqa/script.frost_melancholy_peacock.sh
        container: qc.lic_denim_smart_octopus
  QC.Sec:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client bandit:
        commands:
        - /usr/bin/env sh .sqa/script.isabelline_candid_bat.sh
        container: qc.sec_pansy_reflective_emu
  QC.Sty:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client flake8:
        commands:
        - /usr/bin/env sh .sqa/script.champagne_persistent_caiman.sh
        container: qc.sty_lemon_friendly_giraffe
  QC.Uni:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lemon_lucky_elephant.sh
        container: qc.uni_butter_hardworking_roc
  QC.Ver:
    repos:
      gitlab.cern.ch/batistal/eosc-data-transfer-client get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.emerald_mysterious_mandrill.sh
        container: qc.ver_seafoam_polite_narwhal
timeout: 5400
